// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8ilOliE3jL1yPONfuRgQrJ6qiKgY3wDU',
    appId: '1:367996715898:web:645714b84577735ef70cc3',
    messagingSenderId: '367996715898',
    projectId: 'flutter-huislaw-mynotes',
    authDomain: 'flutter-huislaw-mynotes.firebaseapp.com',
    storageBucket: 'flutter-huislaw-mynotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsdPji_W7fRRj_hqYrzGV18UCi59dTC5g',
    appId: '1:367996715898:android:57be588e008ef531f70cc3',
    messagingSenderId: '367996715898',
    projectId: 'flutter-huislaw-mynotes',
    storageBucket: 'flutter-huislaw-mynotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRFReU20lPpdx77Yiz3e8ce1Kk0YDgUKk',
    appId: '1:367996715898:ios:393d39fcb10aa4aaf70cc3',
    messagingSenderId: '367996715898',
    projectId: 'flutter-huislaw-mynotes',
    storageBucket: 'flutter-huislaw-mynotes.appspot.com',
    iosClientId: '367996715898-33s966b99fqm2r4cqadklafmnir35jof.apps.googleusercontent.com',
    iosBundleId: 'com.huisheng.mynotes',
  );
}
